### ISSUE TITLE
Additional Data for MVT Profile

### ISSUE THREAD

**Issue by mcohenui** [NeighborhoodInfoDC/MVT#3]
@lhendey @ocarena 

- •	Additional Data Asks
    - Labor force data disaggregated by race
    - Look into additional sources for jobs data (LEHD, U6)
    - N’s for home sales
    - Comparison of SNAP and TANF trend lines in CT 47 to DC
    - SNAP and TANF data for children. SNAP and TANF by employment status?
    - Data on neighborhood enrollment. Victoria mentioned it would be difficult using the Urban Ed data. Pointed to a dataset on neighborhood enrollment patterns that the Office of the Deputy Mayor for                 Education released for 2016-17
    - Low-weight birth data
    - Income distributions
    - Age distributions
- •	Questions about data
    - Are owner costs related to increasing tax burden?
    - How would SNAP and TANF trend lines be affected by policy changes?
    - Why does inadequate prenatal care jump in 2016?

**Comment by lhendey** [comment]
@ocarena 

can you begin adding in the new variables for some of these? review the metadata to see what we can pull. 

file:///L:/Metadata/meta_acs_acs_2012_16_dc_sum_tr_tr10.html (income and age distributions ) 
file:///L:/Metadata/meta_vital_births_sum_tr10.html low weight births (should have by race -make sure you get the correct denominator) 

i need to take at look at the others.

**Comment by lhendey** [comment]
@ocarena - denominator for household income is the number of households - "agghsldincome" is the sum of income for households in $$  

please add labels! 

let's create some groupings though -do a proc print on all of the income vars

proc print data=compile_mvt_tabs_tracts_select; 
var [insert list of income vars];
run;  

(proc print can be in a separate program - no need to save the code)   and see what the distribution is for C47. - then create 4-5 buckets that make sense. They don't have to be even but what groupings would give a good picture of the neighborhood? then replace your percentages with those categories.

**Comment by lhendey** [comment]
@ocarena - assume you are still working on the new income categories? Can you also add age vars from the ACS and NCDB?
PopUnder18Years, Pop18_34Years, Pop35_64Years, Pop65andOverYears, TotPop (add 18-34+36-64)
NCDB (file:///L:/Metadata/meta_ncdb_ncdb_sum_tr10.html) : (1980, 90 and 00) popunder18years_1980, pop18to64years_1980, pop65andoveryears
